name: cubisima
favicon: null
layout_spectrum: 0.9704986759461462
typography_spectrum: 0.15336832962930202
title: El Portal Suiza para la Familia Cubana
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fecb45'
    - '#3daa3e'
    - '#2375a3'
    - '#ea0b19'
  brandStrength: 0.625
  lightness: 0.21980910561978817
  saturation: 0.3125
  rhythmicContrast: 0.16301682754419744
purpose: []
